# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 393a2476e48221f9b1416258d68a6a541af99055353eb9cebc83db1f0cb01894d972aa7b16ce7311af510ca5e4d6ef29228283399ad806368b6d7f7c0178a067

test:
  secret_key_base: 821a7ba398179d981f40b46cc3933a1b3026322b005732bd5446661b27bf145caeaee1eac6234d87c95c6a657207d7eddc9c901ed34f966bc7ca8de60cebb1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
